baseURL: "https://hsgamer.github.io/"
defaultContentLanguage: "en"
languageCode: "en"
title: "HSGamer's Blog"
theme: "DoIt"
enableGitInfo: true
enableRobotsTXT: true
timeZone: "Asia/Ho_Chi_Minh"
copyright: "CC BY-NC 4.0"