en:
  weight: 1
  languageCode: "en"
  languageName: "English"
vi:
  weight: 2
  languageCode: "vi"
  languageName: "Tiếng Việt"
  title: "Blog của HSGamer"
  menu:
    main:
      - identifier: "posts"
        name: "Bài Viết"
        url: "/posts/"
        title: ""
        weight: 1
      - identifier: "tags"
        name: "Nhãn"
        url: "/tags/"
        title: ""
        weight: 2
      - identifier: "categories"
        name: "Thể Loại"
        url: "/categories/"
        title: ""
        weight: 3
  params:
    title: "Blog của HSGamer"
    description: "Blog của tôi để nói về những thứ thú vị trong Lập trình, Trò Chơi, Công Nghệ, Cuộc Sống, v.v"
    app:
      title: "Blog của HSGamer"
      noFavicon: false
      svgFavicon: "https://raw.githubusercontent.com/HSGamer/hsgamer.github.io/main/images/logo.svg"
      iconColor: "#5bbad5"
      tileColor: "#da532c"
    header:
      desktopMode: "fixed"
      mobileMode: "auto"
      themeChangeMode: "select"
      title:
        logo: "https://raw.githubusercontent.com/HSGamer/hsgamer.github.io/main/images/logo.svg"
        name: "Blog của HSGamer"
    home:
      rss: 10
      profile:
        enable: true
        gravatarEmail: ""
        avatarURL: "https://raw.githubusercontent.com/HSGamer/hsgamer.github.io/main/images/logo.svg"
        title: "Blog của HSGamer"
        subtitle: "Blog của tôi để nói về những thứ thú vị trong Lập trình, Trò Chơi, Công Nghệ, Cuộc Sống, v.v"
        typeit: true
        social: true
        disclaimer: ""
      posts:
        enable: true
        paginate: 6
        defaultHiddenFromHomePage: false
    page:
      hiddenFromHomePage: false
      hiddenFromSearch: false
      twemoji: false
      lightgallery: false
      ruby: true
      fraction: true
      fontawesome: true
      linkToMarkdown: true
      linkToSource: "https://github.com/HSGamer/Blog/blob/main/content/{path}"
      linkToEdit: "https://github.com/HSGamer/Blog/edit/main/content/{path}"
      linkToReport: "https://github.com/HSGamer/Blog/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/HSGamer/Blog/blob/main/content/{path}|"
      rssFullText: false
      pageStyle: "normal"
      seriesNavigation: true
      outdatedArticleReminder:
        enable: false
        reminder: 90
        warning: 180
      toc:
        enable: true
        keepStatic: true
        auto: true
      math:
        enable: true
        blockLeftDelimiter: ""
        blockRightDelimiter: ""
        inlineLeftDelimiter: ""
        inlineRightDelimiter: ""
        copyTex: true
        mhchem: true
      code:
        copy: true
        maxShownLines: 10
      table:
        sort: true
      mapbox:
        accessToken: ""
        lightStyle: "mapbox://styles/mapbox/light-v9"
        darkStyle: "mapbox://styles/mapbox/dark-v9"
        navigation: true
        geolocate: true
        scale: true
        fullscreen: true
      share:
        enable: true
        Twitter: true
        Facebook: true
      comment:
        enable: true
        giscus:
          enable: true
          dataRepo: "HSGamer/Blog"
          dataRepoId: "R_kgDOIdDFUA"
          dataCategory: "Post Comments"
          dataCategoryId: "DIC_kwDOIdDFUM4CSnWy"
          dataMapping: "pathname"
          dataReactionsEnabled: "1"
          dataEmitMetadata: "0"
          dataInputPosition: "bottom"
          lightTheme: "light"
          darkTheme: "transparent_dark"
          dataLang: "vi"
      seo:
        images: []
        publisher:
          name: ""
          logoUrl: ""
      related:
        enable: true
        count: 5