main:
  - identifier: "posts"
    name: "Posts"
    url: "/posts/"
    title: ""
    weight: 1
  - identifier: "tags"
    name: "Tags"
    url: "/tags/"
    title: ""
    weight: 2
  - identifier: "categories"
    name: "Categories"
    url: "/categories/"
    title: ""
    weight: 3
  - identifier: "series"
    name: "Series"
    url: "/series/"
    title: ""
    weight: 4
