version: "0.2.X"
title: "HSGamer's Blog"
description: "My blog of interests in various topics. Development, Technology, Game, Life, etc."
keywords: ["HSGamer", "Blog"]
defaultTheme: "auto"
gitRepo: "https://github.com/HSGamer/Blog"
fingerprint: "sha256"
dateFormat: "2006-01-02"
images: ["/logo.svg"]
enablePWA: false
license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

app:
  title: "HSGamer's Blog"
  noFavicon: false
  svgFavicon: "/logo.svg"
  iconColor: "#5bbad5"
  tileColor: "#da532c"

search:
  enable: true
  type: "fuse"
  placeholder: ""
  maxResultLength: 10
  snippetLength: 30
  highlightTag: "em"
  absoluteURL: false
  fuse:
    isCaseSensitive: false
    minMatchCharLength: 2
    findAllMatches: false
    location: 0
    threshold: 0.3
    distance: 100
    ignoreLocation: false
    useExtendedSearch: false
    ignoreFieldNorm: false

header:
  desktopMode: "fixed"
  mobileMode: "auto"
  themeChangeMode: "select"
  title:
    logo: "/logo.svg"
    name: "HSGamer's Blog"

footer:
  enable: true
  custom: ''
  hugo: true
  hostedOn: '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>'
  copyright: true
  author: true
  license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

section:
  paginate: 20
  dateFormat: "01-02"
  rss: 10
  recentlyUpdated:
    enable: false
    rss: false
    days: 30
    maxCount: 10

list:
  paginate: 20
  dateFormat: "01-02"
  rss: 10

home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ""
    avatarURL: "/logo.svg"
    title: "HSGamer's Blog"
    subtitle: "My blog of interests in various topics. Development, Technology, Game, Life, etc."
    typeit: true
    social: true
    disclaimer: ""
  posts:
    enable: true
    paginate: 6
    defaultHiddenFromHomePage: false
  
social:
  RSS: true
  Email: "huynhqtienvtag@gmail.com"
  GitHub: "HSGamer"
  Facebook: "huynhquang.tien.33"
  Youtubechannel: "UCT4YTVtGkICHOUcrJN87rgw"
  Patreon: "hsgamer"
  Steam: "76561198124492786"
  Paypal: "HSGamer1234"

page:
  hiddenFromHomePage: false
  hiddenFromSearch: false
  twemoji: false
  lightgallery: false
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: true
  linkToSource: "https://github.com/HSGamer/Blog/blob/main/content/{path}"
  linkToEdit: "https://github.com/HSGamer/Blog/edit/main/content/{path}"
  linkToReport: "https://github.com/HSGamer/Blog/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/HSGamer/Blog/blob/main/content/{path}|"
  rssFullText: false
  pageStyle: "normal"
  seriesNavigation: true
  outdatedArticleReminder:
    enable: false
    reminder: 90
    warning: 180
  toc:
    enable: true
    keepStatic: true
    auto: true
  math:
    enable: true
    blockLeftDelimiter: ""
    blockRightDelimiter: ""
    inlineLeftDelimiter: ""
    inlineRightDelimiter: ""
    copyTex: true
    mhchem: true
  code:
    copy: true
    maxShownLines: 10
  table:
    sort: true
  mapbox:
    accessToken: ""
    lightStyle: "mapbox://styles/mapbox/light-v9"
    darkStyle: "mapbox://styles/mapbox/dark-v9"
    navigation: true
    geolocate: true
    scale: true
    fullscreen: true
  share:
    enable: true
    Twitter: true
    Facebook: true
  comment:
    enable: true
    giscus:
      enable: true
      dataRepo: "HSGamer/Blog"
      dataRepoId: "R_kgDOIdDFUA"
      dataCategory: "Post Comments"
      dataCategoryId: "DIC_kwDOIdDFUM4CSnWy"
      dataMapping: "pathname"
      dataReactionsEnabled: "1"
      dataEmitMetadata: "0"
      dataInputPosition: "bottom"
      lightTheme: "light"
      darkTheme: "transparent_dark"
      dataLang: "en"
  seo:
    images: []
    publisher:
      name: ""
      logoUrl: ""
  related:
    enable: true
    count: 5

sponsor:
  enable: false
  bio: "If you find this post helpful, please consider sponsoring."
  link: "https://paypal.me/HSGamer1234"
  custom: ""

typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: "|"
  duration: -1

seo:
  image: ""
  thumbnailUrl: ""